{
 "title": "Radarr v3",
 "description": "This is a dashboard for Radarr v3 (exportarr does not work with Radarr v2). You will need to install exportarr (https://github.com/onedr0p/exportarr) in order to use this dashboard.\r\n\r\nBased on: https://grafana.com/grafana/dashboards/12530",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Movies Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "radrr_queue_total OR on() vector(0)",
     "legendFormat": "Queued"
    },
    { "expr": "radarr_history_total", "legendFormat": "Completed" }
   ]
  },
  {
   "title": "Movies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "radarr_movie_missing_total", "legendFormat": "Missing" },
    { "expr": "radarr_movie_monitored_total", "legendFormat": "Monitored" },
    { "expr": "radarr_movie_total", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Storage Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "radarr_movie_filesize_total" }
   ]
  },
  {
   "title": "Episode quality",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(radarr_movie_quality_total) by (quality))",
     "legendFormat": "{{ quality }}"
    }
   ]
  },
  {
   "title": "Storage Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "radarr_rootfolder_freespace_bytes",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}