{ pkgs, config, lib, ... }:
with lib;
let
  cfg = config.modules.media.prowlarr;
in
{
  options.modules.media.prowlarr = {
    enable = mkEnableOption "Enables Prowlarr service";

    config = {
      port = mkOption {
        default = 9696;
        type = types.port;
      };
      apiKey = mkOption {
        default = "00000000000000000000000000000000";
        type = types.string;
      };

      radarrConnection = {
        enable = mkEnableOption "enables radarr connection";
      };
    };
  };

#   {
#   "syncLevel": "fullSync",
#   "name": "Radarr",
#   "fields": [
#     {
#       "order": 0,
#       "name": "prowlarrUrl",
#       "label": "Prowlarr Server",
#       "helpText": "Prowlarr server URL as Radarr sees it, including http(s)://, port, and urlbase if needed",
#       "value": "http://indexer",
#       "type": "textbox",
#       "advanced": false,
#       "privacy": "normal",
#       "placeholder": "http://localhost:9696",
#       "isFloat": false
#     },
#     {
#       "order": 1,
#       "name": "baseUrl",
#       "label": "Radarr Server",
#       "helpText": "URL used to connect to Radarr server, including http(s)://, port, and urlbase if required",
#       "value": "http://curator",
#       "type": "textbox",
#       "advanced": false,
#       "privacy": "normal",
#       "placeholder": "http://localhost:7878",
#       "isFloat": false
#     },
#     {
#       "order": 2,
#       "name": "apiKey",
#       "label": "API Key",
#       "helpText": "The ApiKey generated by Radarr in Settings/General",
#       "value": "********",
#       "type": "textbox",
#       "advanced": false,
#       "privacy": "apiKey",
#       "isFloat": false
#     },
#     {
#       "order": 3,
#       "name": "syncCategories",
#       "label": "Sync Categories",
#       "helpText": "Only Indexers that support these categories will be synced",
#       "value": [
#         2000,
#         2010,
#         2020,
#         2030,
#         2040,
#         2045,
#         2050,
#         2060,
#         2070,
#         2080,
#         2090
#       ],
#       "type": "select",
#       "advanced": true,
#       "selectOptions": [
#         {
#           "value": 0,
#           "name": "Other",
#           "order": 0,
#           "hint": "(0)"
#         },
#         {
#           "value": 10,
#           "name": "Other/Misc",
#           "order": 0,
#           "hint": "(10)",
#           "parentValue": 0
#         },
#         {
#           "value": 20,
#           "name": "Other/Hashed",
#           "order": 0,
#           "hint": "(20)",
#           "parentValue": 0
#         },
#         {
#           "value": 1000,
#           "name": "Console",
#           "order": 0,
#           "hint": "(1000)"
#         },
#         {
#           "value": 1010,
#           "name": "Console/NDS",
#           "order": 0,
#           "hint": "(1010)",
#           "parentValue": 1000
#         },
#         {
#           "value": 1020,
#           "name": "Console/PSP",
#           "order": 0,
#           "hint": "(1020)",
#           "parentValue": 1000
#         },
#         {
#           "value": 1030,
#           "name": "Console/Wii",
#           "order": 0,
#           "hint": "(1030)",
#           "parentValue": 1000
#         },
#         {
#           "value": 1040,
#           "name": "Console/XBox",
#           "order": 0,
#           "hint": "(1040)",
#           "parentValue": 1000
#         },
#         {
#           "value": 1050,
#           "name": "Console/XBox 360",
#           "order": 0,
#           "hint": "(1050)",
#           "parentValue": 1000
#         },
#         {
#           "value": 1060,
#           "name": "Console/Wiiware",
#           "order": 0,
#           "hint": "(1060)",
#           "parentValue": 1000
#         },
#         {
#           "value": 1070,
#           "name": "Console/XBox 360 DLC",
#           "order": 0,
#           "hint": "(1070)",
#           "parentValue": 1000
#         },
#         {
#           "value": 1080,
#           "name": "Console/PS3",
#           "order": 0,
#           "hint": "(1080)",
#           "parentValue": 1000
#         },
#         {
#           "value": 1090,
#           "name": "Console/Other",
#           "order": 0,
#           "hint": "(1090)",
#           "parentValue": 1000
#         },
#         {
#           "value": 1110,
#           "name": "Console/3DS",
#           "order": 0,
#           "hint": "(1110)",
#           "parentValue": 1000
#         },
#         {
#           "value": 1120,
#           "name": "Console/PS Vita",
#           "order": 0,
#           "hint": "(1120)",
#           "parentValue": 1000
#         },
#         {
#           "value": 1130,
#           "name": "Console/WiiU",
#           "order": 0,
#           "hint": "(1130)",
#           "parentValue": 1000
#         },
#         {
#           "value": 1140,
#           "name": "Console/XBox One",
#           "order": 0,
#           "hint": "(1140)",
#           "parentValue": 1000
#         },
#         {
#           "value": 1180,
#           "name": "Console/PS4",
#           "order": 0,
#           "hint": "(1180)",
#           "parentValue": 1000
#         },
#         {
#           "value": 2000,
#           "name": "Movies",
#           "order": 0,
#           "hint": "(2000)"
#         },
#         {
#           "value": 2010,
#           "name": "Movies/Foreign",
#           "order": 0,
#           "hint": "(2010)",
#           "parentValue": 2000
#         },
#         {
#           "value": 2020,
#           "name": "Movies/Other",
#           "order": 0,
#           "hint": "(2020)",
#           "parentValue": 2000
#         },
#         {
#           "value": 2030,
#           "name": "Movies/SD",
#           "order": 0,
#           "hint": "(2030)",
#           "parentValue": 2000
#         },
#         {
#           "value": 2040,
#           "name": "Movies/HD",
#           "order": 0,
#           "hint": "(2040)",
#           "parentValue": 2000
#         },
#         {
#           "value": 2045,
#           "name": "Movies/UHD",
#           "order": 0,
#           "hint": "(2045)",
#           "parentValue": 2000
#         },
#         {
#           "value": 2050,
#           "name": "Movies/BluRay",
#           "order": 0,
#           "hint": "(2050)",
#           "parentValue": 2000
#         },
#         {
#           "value": 2060,
#           "name": "Movies/3D",
#           "order": 0,
#           "hint": "(2060)",
#           "parentValue": 2000
#         },
#         {
#           "value": 2070,
#           "name": "Movies/DVD",
#           "order": 0,
#           "hint": "(2070)",
#           "parentValue": 2000
#         },
#         {
#           "value": 2080,
#           "name": "Movies/WEB-DL",
#           "order": 0,
#           "hint": "(2080)",
#           "parentValue": 2000
#         },
#         {
#           "value": 2090,
#           "name": "Movies/x265",
#           "order": 0,
#           "hint": "(2090)",
#           "parentValue": 2000
#         },
#         {
#           "value": 3000,
#           "name": "Audio",
#           "order": 0,
#           "hint": "(3000)"
#         },
#         {
#           "value": 3010,
#           "name": "Audio/MP3",
#           "order": 0,
#           "hint": "(3010)",
#           "parentValue": 3000
#         },
#         {
#           "value": 3020,
#           "name": "Audio/Video",
#           "order": 0,
#           "hint": "(3020)",
#           "parentValue": 3000
#         },
#         {
#           "value": 3030,
#           "name": "Audio/Audiobook",
#           "order": 0,
#           "hint": "(3030)",
#           "parentValue": 3000
#         },
#         {
#           "value": 3040,
#           "name": "Audio/Lossless",
#           "order": 0,
#           "hint": "(3040)",
#           "parentValue": 3000
#         },
#         {
#           "value": 3050,
#           "name": "Audio/Other",
#           "order": 0,
#           "hint": "(3050)",
#           "parentValue": 3000
#         },
#         {
#           "value": 3060,
#           "name": "Audio/Foreign",
#           "order": 0,
#           "hint": "(3060)",
#           "parentValue": 3000
#         },
#         {
#           "value": 4000,
#           "name": "PC",
#           "order": 0,
#           "hint": "(4000)"
#         },
#         {
#           "value": 4010,
#           "name": "PC/0day",
#           "order": 0,
#           "hint": "(4010)",
#           "parentValue": 4000
#         },
#         {
#           "value": 4020,
#           "name": "PC/ISO",
#           "order": 0,
#           "hint": "(4020)",
#           "parentValue": 4000
#         },
#         {
#           "value": 4030,
#           "name": "PC/Mac",
#           "order": 0,
#           "hint": "(4030)",
#           "parentValue": 4000
#         },
#         {
#           "value": 4040,
#           "name": "PC/Mobile-Other",
#           "order": 0,
#           "hint": "(4040)",
#           "parentValue": 4000
#         },
#         {
#           "value": 4050,
#           "name": "PC/Games",
#           "order": 0,
#           "hint": "(4050)",
#           "parentValue": 4000
#         },
#         {
#           "value": 4060,
#           "name": "PC/Mobile-iOS",
#           "order": 0,
#           "hint": "(4060)",
#           "parentValue": 4000
#         },
#         {
#           "value": 4070,
#           "name": "PC/Mobile-Android",
#           "order": 0,
#           "hint": "(4070)",
#           "parentValue": 4000
#         },
#         {
#           "value": 5000,
#           "name": "TV",
#           "order": 0,
#           "hint": "(5000)"
#         },
#         {
#           "value": 5010,
#           "name": "TV/WEB-DL",
#           "order": 0,
#           "hint": "(5010)",
#           "parentValue": 5000
#         },
#         {
#           "value": 5020,
#           "name": "TV/Foreign",
#           "order": 0,
#           "hint": "(5020)",
#           "parentValue": 5000
#         },
#         {
#           "value": 5030,
#           "name": "TV/SD",
#           "order": 0,
#           "hint": "(5030)",
#           "parentValue": 5000
#         },
#         {
#           "value": 5040,
#           "name": "TV/HD",
#           "order": 0,
#           "hint": "(5040)",
#           "parentValue": 5000
#         },
#         {
#           "value": 5045,
#           "name": "TV/UHD",
#           "order": 0,
#           "hint": "(5045)",
#           "parentValue": 5000
#         },
#         {
#           "value": 5050,
#           "name": "TV/Other",
#           "order": 0,
#           "hint": "(5050)",
#           "parentValue": 5000
#         },
#         {
#           "value": 5060,
#           "name": "TV/Sport",
#           "order": 0,
#           "hint": "(5060)",
#           "parentValue": 5000
#         },
#         {
#           "value": 5070,
#           "name": "TV/Anime",
#           "order": 0,
#           "hint": "(5070)",
#           "parentValue": 5000
#         },
#         {
#           "value": 5080,
#           "name": "TV/Documentary",
#           "order": 0,
#           "hint": "(5080)",
#           "parentValue": 5000
#         },
#         {
#           "value": 5090,
#           "name": "TV/x265",
#           "order": 0,
#           "hint": "(5090)",
#           "parentValue": 5000
#         },
#         {
#           "value": 6000,
#           "name": "XXX",
#           "order": 0,
#           "hint": "(6000)"
#         },
#         {
#           "value": 6010,
#           "name": "XXX/DVD",
#           "order": 0,
#           "hint": "(6010)",
#           "parentValue": 6000
#         },
#         {
#           "value": 6020,
#           "name": "XXX/WMV",
#           "order": 0,
#           "hint": "(6020)",
#           "parentValue": 6000
#         },
#         {
#           "value": 6030,
#           "name": "XXX/XviD",
#           "order": 0,
#           "hint": "(6030)",
#           "parentValue": 6000
#         },
#         {
#           "value": 6040,
#           "name": "XXX/x264",
#           "order": 0,
#           "hint": "(6040)",
#           "parentValue": 6000
#         },
#         {
#           "value": 6045,
#           "name": "XXX/UHD",
#           "order": 0,
#           "hint": "(6045)",
#           "parentValue": 6000
#         },
#         {
#           "value": 6050,
#           "name": "XXX/Pack",
#           "order": 0,
#           "hint": "(6050)",
#           "parentValue": 6000
#         },
#         {
#           "value": 6060,
#           "name": "XXX/ImageSet",
#           "order": 0,
#           "hint": "(6060)",
#           "parentValue": 6000
#         },
#         {
#           "value": 6070,
#           "name": "XXX/Other",
#           "order": 0,
#           "hint": "(6070)",
#           "parentValue": 6000
#         },
#         {
#           "value": 6080,
#           "name": "XXX/SD",
#           "order": 0,
#           "hint": "(6080)",
#           "parentValue": 6000
#         },
#         {
#           "value": 6090,
#           "name": "XXX/WEB-DL",
#           "order": 0,
#           "hint": "(6090)",
#           "parentValue": 6000
#         },
#         {
#           "value": 7000,
#           "name": "Books",
#           "order": 0,
#           "hint": "(7000)"
#         },
#         {
#           "value": 7010,
#           "name": "Books/Mags",
#           "order": 0,
#           "hint": "(7010)",
#           "parentValue": 7000
#         },
#         {
#           "value": 7020,
#           "name": "Books/EBook",
#           "order": 0,
#           "hint": "(7020)",
#           "parentValue": 7000
#         },
#         {
#           "value": 7030,
#           "name": "Books/Comics",
#           "order": 0,
#           "hint": "(7030)",
#           "parentValue": 7000
#         },
#         {
#           "value": 7040,
#           "name": "Books/Technical",
#           "order": 0,
#           "hint": "(7040)",
#           "parentValue": 7000
#         },
#         {
#           "value": 7050,
#           "name": "Books/Other",
#           "order": 0,
#           "hint": "(7050)",
#           "parentValue": 7000
#         },
#         {
#           "value": 7060,
#           "name": "Books/Foreign",
#           "order": 0,
#           "hint": "(7060)",
#           "parentValue": 7000
#         },
#         {
#           "value": 8000,
#           "name": "Other",
#           "order": 0,
#           "hint": "(8000)"
#         },
#         {
#           "value": 8010,
#           "name": "Other/Misc",
#           "order": 0,
#           "hint": "(8010)",
#           "parentValue": 8000
#         },
#         {
#           "value": 8020,
#           "name": "Other/Hashed",
#           "order": 0,
#           "hint": "(8020)",
#           "parentValue": 8000
#         }
#       ],
#       "privacy": "normal",
#       "isFloat": false
#     },
#     {
#       "order": 4,
#       "name": "syncRejectBlocklistedTorrentHashesWhileGrabbing",
#       "label": "Sync Reject Blocklisted Torrent Hashes While Grabbing",
#       "helpText": "If a torrent is blocked by hash it may not properly be rejected during RSS/Search for some indexers, enabling this will allow it to be rejected after the torrent is grabbed, but before it is sent to the client.",
#       "value": false,
#       "type": "checkbox",
#       "advanced": true,
#       "privacy": "normal",
#       "isFloat": false
#     }
#   ],
#   "implementationName": "Radarr",
#   "implementation": "Radarr",
#   "configContract": "RadarrSettings",
#   "infoLink": "https://wiki.servarr.com/prowlarr/supported#radarr",
#   "tags": [],
#   "id": 1
# }

  config = mkIf cfg.enable {
    services.prowlarr.enable = true;

    system.activationScripts.makeProwlarrConfig =
      let
        configFile = pkgs.writeTextFile {
          name = "prowlarr-config.xml";
          text = ''
            <Config>
              <BindAddress>*</BindAddress>
              <Port>${toString cfg.config.port}</Port>
              <ApiKey>${cfg.config.apiKey}</ApiKey>
              <AuthenticationMethod>External</AuthenticationMethod>
              <LogLevel>info</LogLevel>
              <AnalyticsEnabled>False</AnalyticsEnabled>
              <LogDbEnabled>False</LogDbEnabled>
              <InstanceName>Prowlarr</InstanceName>
            </Config>'';
        };
        owner = "prowlarr";
        group = "prowlarr";
        outputFile = "/var/lib/prowlarr/config.xml";
      in
      lib.stringAfter [ "var" ] ''
        ${pkgs.coreutils}/bin/cp ${configFile} ${outputFile}
        ${pkgs.coreutils}/bin/chown ${owner}:${group} ${outputFile}
        ${pkgs.coreutils}/bin/chmod 644 ${outputFile}
      '';
  };
}
