name: Cachix
on:
  push:
  pull_request:
jobs:
  cachix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v21
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: samjwillis97
          authToken: "${{secrets.CACHIX_AUTH_TOKEN}}"
      - name: Build Coder Container
        run: nix build -L '.#homeConfigurations.coder-container.activationPackage'
      - name: Push Coder Container
        run: cachix push samjwillis97 ./result
      - name: Delete Coder Container
        run: rm -rf ./result
      - name: Build Personal Desktop
        run: nix build -L '.#nixosConfigurations.personal-desktop.activationPackage'
      - name: Push Personal Desktop
        run: cachix push samjwillis97 ./result
