name: "//services/coder: push"

on:
  push:
    branches:
      - main
    paths:
      - "services/coder/templates/**"
      - ".github/workflows/coder-templates-push.yml"

  # workflow_dispatch:
  # schedule:
  # * is a special character in YAML so you have to quote this string
  # run this every day at 4:00am
  # - cron: "0 4 * * *"

# Cancel in-progress runs for pull requests when developers push
# additional changes
# concurrency:
#   group: ${{ github.workflow }}-services-dev-ghuntley-templates-push-${{ github.ref }}
#   cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  services-coder-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Connect to Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Check connection
        run: tailscale status | grep -q work-coder-vm
#      - name: Get short commit SHA # to use as template version name
#        id: vars
#        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

#      - name: "Install latest version of Coder"
#        run: |
#          curl -L https://coder.com/install.sh | sh

#      - name: "Push template"
#        run: |
#          cd services/dev-ghuntley/templates

#          coder templates push --directory ./ubuntu \
#            --name ${{ steps.vars.outputs.sha_short }} \
#            --yes

#          coder templates push --directory ./ubuntu-vnc \
#            --name ${{ steps.vars.outputs.sha_short }} \
#            --yes

#          coder templates push --directory ./nix \
#            --name ${{ steps.vars.outputs.sha_short }} \
#            --yes

#          coder templates push --directory ./macos \
#            --name ${{ steps.vars.outputs.sha_short }} \
#            --yes

#          #coder templates push --directory ./gcp-windows-server-2022 \
#          #  --name ${{ steps.vars.outputs.sha_short }} \
#          #  --yes

#          coder templates push --directory ./alpine \
#            --name ${{ steps.vars.outputs.sha_short }} \
#            --yes

#        env:
#          # Consumed by Coder CLI
#          CODER_URL: http://work-coder-vm
#          CODER_SESSION_TOKEN: ${{ secrets.DEV_GHUNTLEY_CODER_SESSION_TOKEN }}
