name: Build & Deploy
# on:
# push:
#   branches:
#     - main
# pull_request:
#   branches:
#     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo rm -rf /opt&
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v21
      - uses: cachix/cachix-action@v12
        with:
          name: samjwillis97-nix-configs
          authToken: "${{ secrets.CACHIX_TOKEN}}"
      - name: Build
        run: nix build -L
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cachix push samjwillis97-nix-configs ./result
      # TODO: Investigate  - Look at Domen's repo
